import Head from 'next/head'
import { PostCard, Categories, PostWidget, Hero, SearchBar } from '../components'
import { getPosts, getAllPosts } from '../services'
import { FeaturedPosts } from '../sections';
import Link from 'next/link';




export default function Home( { posts, allPosts }) {

  return (
    <>
    <div className='container mx-auto px-10 mb-8'>
      <Head>
        <title>Sertan Hikes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <FeaturedPosts />
      <SearchBar posts={ allPosts } />
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
        <div className='lg:col-span-8 col-span-1'>
          {posts.map((post, i) => <PostCard post={post} key={i} />)}
          <div className='flex justify-center p-20'>
            <button className='py-4 transition duration-500 transform hover:-translate-y-1
            inline-block bg-blue-500 
            drop-shadow-lg text-md rounded-lg text-white px-8 py-3 cursor-pointer'>
            <Link href='/all-blogs'>View All Blogs</Link></button>
          </div>
        </div>
        <div className="lg:col-span-4 col-span-4">
          <div className='lg:sticky relative top-8'>
              <PostWidget />
              <Categories /> 
          </div>
        </div>
      </div>
    </div>
    </>
  )
}

export async function getStaticProps() {
  const posts = (await getPosts()) || [];
  const allPosts = (await getAllPosts()) || [];

  return {
    props: { posts, allPosts }
  }

}